export const commercialKeys = {
  all: ['commercial'] as const,
  crmEnabled: () => [...commercialKeys.all, 'crm-enabled'] as const,
  proposalsEnabled: () => [...commercialKeys.all, 'proposals-enabled'] as const,
  stages: () => [...commercialKeys.all, 'pipeline-stages'] as const,
  leads: (filters?: Record<string, unknown>) => [...commercialKeys.all, 'leads', filters ?? {}] as const,
  lead: (id: string) => [...commercialKeys.all, 'lead', id] as const,
  activities: (leadId: string) => [...commercialKeys.all, 'activities', leadId] as const,
  conversation: (leadId: string) => [...commercialKeys.all, 'conversation', leadId] as const,
  scoring: (leadId: string) => [...commercialKeys.all, 'scoring', leadId] as const,
  fieldDefinitions: () => [...commercialKeys.all, 'field-definitions'] as const,
  lossReasons: () => [...commercialKeys.all, 'loss-reasons'] as const,
  erpOptions: () => [...commercialKeys.all, 'erp-options'] as const,
  proposal: (id: string) => [...commercialKeys.all, 'proposal', id] as const,
  dashboard: (filters?: Record<string, unknown>) => [...commercialKeys.all, 'dashboard', filters ?? {}] as const,
  owners: () => [...commercialKeys.all, 'owners'] as const,
  motorConfig: () => [...commercialKeys.all, 'motor-config'] as const,
  notifications: () => [...commercialKeys.all, 'notifications'] as const,
};
