steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - -f
      - scripts/deploy/overlay-financial-entries-fix/Dockerfile
      - .
images:
  - ${_IMAGE}
